stages:
  - build
  - test
  - check

include:
# Issue check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/check-issue@~latest

# Build
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      anod-args: run build_$ACI_TRACK --latest
      cpus: 8
      image: pe-base
      save-component: true

# Testing
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      job-name: lal-refactor
      anod-args: run test_$ACI_TRACK
      image: pe-base
